// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzgFez9U6hI1m3x_cdREr--uAlwH6KXys',
    appId: '1:929877352005:web:e7b4684f6af338ab2e4d2c',
    messagingSenderId: '929877352005',
    projectId: 'example-d8dfc',
    authDomain: 'example-d8dfc.firebaseapp.com',
    storageBucket: 'example-d8dfc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9aQ92gs-6CxilEZr26GbNgpqj0K1A1kk',
    appId: '1:929877352005:android:014d356cd9c866ca2e4d2c',
    messagingSenderId: '929877352005',
    projectId: 'example-d8dfc',
    storageBucket: 'example-d8dfc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzgFez9U6hI1m3x_cdREr--uAlwH6KXys',
    appId: '1:929877352005:web:d3489ead8f02e0b32e4d2c',
    messagingSenderId: '929877352005',
    projectId: 'example-d8dfc',
    authDomain: 'example-d8dfc.firebaseapp.com',
    storageBucket: 'example-d8dfc.firebasestorage.app',
  );
}
