// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8g1xXO2H8RDaDL5AecVOqnxEbydHtVlM',
    appId: '1:849538589191:web:1e6378812366be2f6380a2',
    messagingSenderId: '849538589191',
    projectId: 'push1-4bdd1',
    authDomain: 'push1-4bdd1.firebaseapp.com',
    storageBucket: 'push1-4bdd1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZY7icHCRkoFi-Ue7xVA6_vL09YJp8_tg',
    appId: '1:849538589191:android:949f22343a9fe6226380a2',
    messagingSenderId: '849538589191',
    projectId: 'push1-4bdd1',
    storageBucket: 'push1-4bdd1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8g1xXO2H8RDaDL5AecVOqnxEbydHtVlM',
    appId: '1:849538589191:web:28998156b80406bf6380a2',
    messagingSenderId: '849538589191',
    projectId: 'push1-4bdd1',
    authDomain: 'push1-4bdd1.firebaseapp.com',
    storageBucket: 'push1-4bdd1.firebasestorage.app',
  );
}
