// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlFvtFmtKSnc08aT821wQl3XE0syAM5cA',
    appId: '1:1000544007375:web:45691e5f583350db9f33ba',
    messagingSenderId: '1000544007375',
    projectId: 'authen-5b60a',
    authDomain: 'authen-5b60a.firebaseapp.com',
    storageBucket: 'authen-5b60a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA4jAnSY2zyiAH3H7Fc5F8gK2PhpfgfUc',
    appId: '1:1000544007375:android:63d21d590c399b4c9f33ba',
    messagingSenderId: '1000544007375',
    projectId: 'authen-5b60a',
    storageBucket: 'authen-5b60a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEqiL0bDL_-A2m0CK0Wyx74c9QHknc2Pc',
    appId: '1:1000544007375:ios:263b7161ac0a8f099f33ba',
    messagingSenderId: '1000544007375',
    projectId: 'authen-5b60a',
    storageBucket: 'authen-5b60a.firebasestorage.app',
    iosBundleId: 'com.example.authen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEqiL0bDL_-A2m0CK0Wyx74c9QHknc2Pc',
    appId: '1:1000544007375:ios:263b7161ac0a8f099f33ba',
    messagingSenderId: '1000544007375',
    projectId: 'authen-5b60a',
    storageBucket: 'authen-5b60a.firebasestorage.app',
    iosBundleId: 'com.example.authen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlFvtFmtKSnc08aT821wQl3XE0syAM5cA',
    appId: '1:1000544007375:web:2aa9b897505aa5b79f33ba',
    messagingSenderId: '1000544007375',
    projectId: 'authen-5b60a',
    authDomain: 'authen-5b60a.firebaseapp.com',
    storageBucket: 'authen-5b60a.firebasestorage.app',
  );
}
