// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQDdAEJdJIkQpCR2VlIGpf-jiBnbQU808',
    appId: '1:420612617755:web:55acf82f532c102935aabe',
    messagingSenderId: '420612617755',
    projectId: 'realtime-b1a36',
    authDomain: 'realtime-b1a36.firebaseapp.com',
    storageBucket: 'realtime-b1a36.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwW9ZavtI6l0y8x0mjagOmZfDGaXkfQaY',
    appId: '1:420612617755:android:5a21d3437055da4035aabe',
    messagingSenderId: '420612617755',
    projectId: 'realtime-b1a36',
    storageBucket: 'realtime-b1a36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVY9ex-9qpr0u_YjeTD2h5ni7x1mFXJHo',
    appId: '1:420612617755:ios:8a1756f2e90ad47d35aabe',
    messagingSenderId: '420612617755',
    projectId: 'realtime-b1a36',
    storageBucket: 'realtime-b1a36.firebasestorage.app',
    iosBundleId: 'com.example.realtime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVY9ex-9qpr0u_YjeTD2h5ni7x1mFXJHo',
    appId: '1:420612617755:ios:8a1756f2e90ad47d35aabe',
    messagingSenderId: '420612617755',
    projectId: 'realtime-b1a36',
    storageBucket: 'realtime-b1a36.firebasestorage.app',
    iosBundleId: 'com.example.realtime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQDdAEJdJIkQpCR2VlIGpf-jiBnbQU808',
    appId: '1:420612617755:web:090547cf704b81da35aabe',
    messagingSenderId: '420612617755',
    projectId: 'realtime-b1a36',
    authDomain: 'realtime-b1a36.firebaseapp.com',
    storageBucket: 'realtime-b1a36.firebasestorage.app',
  );
}
