// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2I2tQiz6UtipuY3Zq1fqCvYs-vgjsMYQ',
    appId: '1:1011648055709:web:703d72932618b654808774',
    messagingSenderId: '1011648055709',
    projectId: 'local-f1548',
    authDomain: 'local-f1548.firebaseapp.com',
    storageBucket: 'local-f1548.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrEtKi06Gh1pANIntHU2IW6ltQ4hZ0_m4',
    appId: '1:1011648055709:android:6d0dfcd13972882d808774',
    messagingSenderId: '1011648055709',
    projectId: 'local-f1548',
    storageBucket: 'local-f1548.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2I2tQiz6UtipuY3Zq1fqCvYs-vgjsMYQ',
    appId: '1:1011648055709:web:2c7d9dccf862630c808774',
    messagingSenderId: '1011648055709',
    projectId: 'local-f1548',
    authDomain: 'local-f1548.firebaseapp.com',
    storageBucket: 'local-f1548.firebasestorage.app',
  );
}
