// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa59Bpentu8SfgsrcQ5tgMsJO7nK6GF2o',
    appId: '1:540383854829:web:81939d705956c8b9a1cce4',
    messagingSenderId: '540383854829',
    projectId: 'message-2d18c',
    authDomain: 'message-2d18c.firebaseapp.com',
    storageBucket: 'message-2d18c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmYj8OGTx3urzxqQGVK_mj2C2SOu0AQjA',
    appId: '1:540383854829:android:286e216888aeeebea1cce4',
    messagingSenderId: '540383854829',
    projectId: 'message-2d18c',
    storageBucket: 'message-2d18c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqh8QF033NC-f74l1oGW5q3vQHyJ83ksw',
    appId: '1:540383854829:ios:1d6401620c041977a1cce4',
    messagingSenderId: '540383854829',
    projectId: 'message-2d18c',
    storageBucket: 'message-2d18c.firebasestorage.app',
    iosBundleId: 'com.example.message',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqh8QF033NC-f74l1oGW5q3vQHyJ83ksw',
    appId: '1:540383854829:ios:1d6401620c041977a1cce4',
    messagingSenderId: '540383854829',
    projectId: 'message-2d18c',
    storageBucket: 'message-2d18c.firebasestorage.app',
    iosBundleId: 'com.example.message',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa59Bpentu8SfgsrcQ5tgMsJO7nK6GF2o',
    appId: '1:540383854829:web:cc95f741781b494fa1cce4',
    messagingSenderId: '540383854829',
    projectId: 'message-2d18c',
    authDomain: 'message-2d18c.firebaseapp.com',
    storageBucket: 'message-2d18c.firebasestorage.app',
  );
}
