// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyD1oD4TQDMbVTDRXxFOWY23v4EpoPBhk',
    appId: '1:93746475551:web:7bc355b3ad3a54610f5b2a',
    messagingSenderId: '93746475551',
    projectId: 'cloudactivity-15f4b',
    authDomain: 'cloudactivity-15f4b.firebaseapp.com',
    storageBucket: 'cloudactivity-15f4b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsquPa_QGudSBzyTvbuq294_dSAd_loBA',
    appId: '1:93746475551:android:cb3e51b8688b31a70f5b2a',
    messagingSenderId: '93746475551',
    projectId: 'cloudactivity-15f4b',
    storageBucket: 'cloudactivity-15f4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk8CtIjlQqbCETFUKFqEAnZ0ZPcMTG1MY',
    appId: '1:93746475551:ios:7660ffa44cf233d00f5b2a',
    messagingSenderId: '93746475551',
    projectId: 'cloudactivity-15f4b',
    storageBucket: 'cloudactivity-15f4b.firebasestorage.app',
    iosBundleId: 'com.example.cloudactivity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk8CtIjlQqbCETFUKFqEAnZ0ZPcMTG1MY',
    appId: '1:93746475551:ios:7660ffa44cf233d00f5b2a',
    messagingSenderId: '93746475551',
    projectId: 'cloudactivity-15f4b',
    storageBucket: 'cloudactivity-15f4b.firebasestorage.app',
    iosBundleId: 'com.example.cloudactivity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyD1oD4TQDMbVTDRXxFOWY23v4EpoPBhk',
    appId: '1:93746475551:web:d307d1df093121fb0f5b2a',
    messagingSenderId: '93746475551',
    projectId: 'cloudactivity-15f4b',
    authDomain: 'cloudactivity-15f4b.firebaseapp.com',
    storageBucket: 'cloudactivity-15f4b.firebasestorage.app',
  );
}
