// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGFD8I6VEErkcG70w0nGJnKQPHI_3iItI',
    appId: '1:999673283311:web:05c660b994a020ad4ed11a',
    messagingSenderId: '999673283311',
    projectId: 'fir-b8b3e',
    authDomain: 'fir-b8b3e.firebaseapp.com',
    storageBucket: 'fir-b8b3e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbwTS0fUVv_p6DG4e77OmEl1fLNGAS1jY',
    appId: '1:999673283311:android:55aa77cc4dca807e4ed11a',
    messagingSenderId: '999673283311',
    projectId: 'fir-b8b3e',
    storageBucket: 'fir-b8b3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAPfEL4qhLV5Xq5hvTr0VHLuDT2wgP_E4',
    appId: '1:999673283311:ios:301d6f0493f953354ed11a',
    messagingSenderId: '999673283311',
    projectId: 'fir-b8b3e',
    storageBucket: 'fir-b8b3e.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAPfEL4qhLV5Xq5hvTr0VHLuDT2wgP_E4',
    appId: '1:999673283311:ios:301d6f0493f953354ed11a',
    messagingSenderId: '999673283311',
    projectId: 'fir-b8b3e',
    storageBucket: 'fir-b8b3e.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGFD8I6VEErkcG70w0nGJnKQPHI_3iItI',
    appId: '1:999673283311:web:ec396329485a92434ed11a',
    messagingSenderId: '999673283311',
    projectId: 'fir-b8b3e',
    authDomain: 'fir-b8b3e.firebaseapp.com',
    storageBucket: 'fir-b8b3e.firebasestorage.app',
  );
}
