// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBYTa6tdZ5cTiOkgwDqP-ee2dY2wwsI-Y',
    appId: '1:690884829873:web:89cd6fbfddb8b65123b890',
    messagingSenderId: '690884829873',
    projectId: 'sample-4d90b',
    authDomain: 'sample-4d90b.firebaseapp.com',
    storageBucket: 'sample-4d90b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWnUMtjaYN27mo-ADIpSpc-keyy1ILQb8',
    appId: '1:690884829873:android:30f6008d4e31e03e23b890',
    messagingSenderId: '690884829873',
    projectId: 'sample-4d90b',
    storageBucket: 'sample-4d90b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAwtBsdsN25kiO3-1wTRcdlsq_VioiuqU',
    appId: '1:690884829873:ios:99f581d83b4ca5db23b890',
    messagingSenderId: '690884829873',
    projectId: 'sample-4d90b',
    storageBucket: 'sample-4d90b.firebasestorage.app',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAwtBsdsN25kiO3-1wTRcdlsq_VioiuqU',
    appId: '1:690884829873:ios:99f581d83b4ca5db23b890',
    messagingSenderId: '690884829873',
    projectId: 'sample-4d90b',
    storageBucket: 'sample-4d90b.firebasestorage.app',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBYTa6tdZ5cTiOkgwDqP-ee2dY2wwsI-Y',
    appId: '1:690884829873:web:88fd060b6f3e19f723b890',
    messagingSenderId: '690884829873',
    projectId: 'sample-4d90b',
    authDomain: 'sample-4d90b.firebaseapp.com',
    storageBucket: 'sample-4d90b.firebasestorage.app',
  );
}
