// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI3ksPRdZoi8X0DrK9dEb6cT6Fp8m_E4c',
    appId: '1:809158354135:web:4d5131d9c4d19a5708fc92',
    messagingSenderId: '809158354135',
    projectId: 'cloudfirestore-350d3',
    authDomain: 'cloudfirestore-350d3.firebaseapp.com',
    storageBucket: 'cloudfirestore-350d3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbqoT9OxUqcHhqD9ttKSUn7i2mrPvbUVo',
    appId: '1:809158354135:android:abc0a6eb8beb77d308fc92',
    messagingSenderId: '809158354135',
    projectId: 'cloudfirestore-350d3',
    storageBucket: 'cloudfirestore-350d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsdEt76WypHAYJgMAH89_1H77I389wvFo',
    appId: '1:809158354135:ios:2fcfc67b32017abd08fc92',
    messagingSenderId: '809158354135',
    projectId: 'cloudfirestore-350d3',
    storageBucket: 'cloudfirestore-350d3.firebasestorage.app',
    iosBundleId: 'com.example.cloudfirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsdEt76WypHAYJgMAH89_1H77I389wvFo',
    appId: '1:809158354135:ios:2fcfc67b32017abd08fc92',
    messagingSenderId: '809158354135',
    projectId: 'cloudfirestore-350d3',
    storageBucket: 'cloudfirestore-350d3.firebasestorage.app',
    iosBundleId: 'com.example.cloudfirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI3ksPRdZoi8X0DrK9dEb6cT6Fp8m_E4c',
    appId: '1:809158354135:web:c25801afd6b8a73908fc92',
    messagingSenderId: '809158354135',
    projectId: 'cloudfirestore-350d3',
    authDomain: 'cloudfirestore-350d3.firebaseapp.com',
    storageBucket: 'cloudfirestore-350d3.firebasestorage.app',
  );
}
